sudo: false
language: python
python:
    - '3.5'
# command to install dependencies
install: "pip install -U devpi"

script: 
    - devpi use https://devpi.net/nicoddemus/dev
    - devpi test py==1.4.33 --tox-args "-- --color=yes"
