sudo: false
language: python
python:
    - '3.6'
# command to install dependencies
install: "pip install -U devpi"

script: 
    - devpi use https://devpi.net/obestwalter/dev
    - devpi test tox==2.6.0.dev1
