sudo: false
language: python
python:
    - '3.5'
# command to install dependencies
install: "pip install -U devpi"

script: 
    - devpi use https://devpi.net/nicoddemus/dev
    - devpi test pytest-xdist==1.14.1.dev1
