install:
  - echo Installed Pythons
  - dir c:\Python*

  - C:\Python35\python -m pip install devpi

build: false  # Not a C# project, build stuff at the test step instead.

test_script:  
  - C:\Python35\python -m devpi use https://devpi.net/nicoddemus/dev
  - C:\Python35\python -m devpi test pytest==2.8.5
